redis:
    image: redis

web:
    build: php
    links:
        - redis
    volumes:
        - .:/var/www:ro
        - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
        VIRTUAL_HOST: packagist.adamharvey.name
        LETSENCRYPT_HOST: packagist.adamharvey.name
        LETSENCRYPT_EMAIL: aharvey@php.net
  
# vim: set et ts=4 sw=4:
