version: '2'

services:
    redis:
        image: redis

    web:
        build: 
            context: .
            dockerfile: php/Dockerfile
        ports:
            - 8070:80
        links:
            - redis
        volumes:
            - .:/var/www:ro
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
  
# vim: set et ts=4 sw=4:
